# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

class FileIO:
    @staticmethod
    def from_props(props: dict[str, str]) -> "FileIO": ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def new_input(self, path: str) -> "InputFile": ...
    def new_output(self, path: str) -> "OutputFile": ...
    def __repr__(self) -> str: ...

class InputFile:
    def location(self) -> str: ...
    def exists(self) -> bool: ...
    def read(self) -> bytes: ...
    def metadata(self) -> dict[str, int]: ...
    def __repr__(self) -> str: ...

class OutputFile:
    def location(self) -> str: ...
    def write(self, data: bytes) -> None: ...
    def __repr__(self) -> str: ...
