# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from typing import Any

class PyManifest:
    def entries(self) -> list[PyManifestEntry]: ...

class PyFieldSummary:
    @property
    def contains_null(self) -> bool: ...
    @property
    def contains_nan(self) -> bool | None: ...
    @property
    def lower_bound(self) -> bytes | None: ...
    @property
    def upper_bound(self) -> bytes | None: ...

class PyManifestFile:
    @property
    def manifest_path(self) -> str: ...
    @property
    def manifest_length(self) -> int: ...
    @property
    def partition_spec_id(self) -> int: ...
    @property
    def content(self) -> int: ...
    @property
    def sequence_number(self) -> int: ...
    @property
    def min_sequence_number(self) -> int: ...
    @property
    def added_snapshot_id(self) -> int: ...
    @property
    def added_files_count(self) -> int | None: ...
    @property
    def existing_files_count(self) -> int | None: ...
    @property
    def deleted_files_count(self) -> int | None: ...
    @property
    def added_rows_count(self) -> int | None: ...
    @property
    def existing_rows_count(self) -> int | None: ...
    @property
    def deleted_rows_count(self) -> int | None: ...
    @property
    def partitions(self) -> list[PyFieldSummary]: ...
    @property
    def key_metadata(self) -> bytes | None: ...

class PyManifestEntry:
    @property
    def status(self) -> int: ...
    @property
    def snapshot_id(self) -> int | None: ...
    @property
    def sequence_number(self) -> int | None: ...
    @property
    def file_sequence_number(self) -> int | None: ...
    @property
    def data_file(self) -> Any: ...

class PyManifestList:
    def entries(self) -> list[PyManifestFile]: ...

def read_manifest_entries(bs: bytes) -> PyManifest: ...
def read_manifest_list(bs: bytes) -> PyManifestList: ...
