# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from typing import Any

FieldInfo = dict[str, int | str | bool]


class Schema:
    @staticmethod
    def from_json(s: str) -> "Schema": ...
    def schema_id(self) -> int: ...
    def highest_field_id(self) -> int: ...
    def column_names(self) -> list[str]: ...
    def identifier_field_ids(self) -> list[int]: ...
    def find_field_by_name(self, name: str) -> FieldInfo | None: ...
    def field_by_id(self, field_id: int) -> FieldInfo: ...
    def to_json(self) -> str: ...
    def to_arrow_schema(self) -> Any: ...
    def __arrow_c_schema__(self) -> Any: ...
    def _capsule(self) -> Any: ...
    def __repr__(self) -> str: ...
